---
server:
  sqs:
    enabled: true
    port: 3001
    keys:
      - accesskey: DEV_ACCESS_KEY_ID
        secretkey: DEV_SECRET_ACCESS_KEY

# Allow for tls based servers
#  tls:
#    cert: /shared/ssl-certs/bundle.pem
#    private-key: /shared/ssl-certs/pk.pem


  dashboard:
    enabled: true
    port: 3000

  sqlite:
    path: smoothmq.sqlite